Add task 3.1
Donfa1con/made_2019_algo pull request #2
Opened 2019-11-02 19:40 UTC by Donfa1con

2019-11-09 00:47 UTC, ylyubimov requested changes

2019-11-09 00:47 UTC, ylyubimov commented on hw2/task_3_1/main.cpp
> +        std::cin >> data[i];
В задании сказано, что весь массив целиком прочитать нельзя. Нужно считывать порядка K элементов.

2019-11-09 00:48 UTC, ylyubimov requested changes
Перепеши, чтобы не читать весь массив.

И перепризови меня в ревью

2019-11-09 07:51 UTC, Donfa1con commented on hw2/task_3_1/main.cpp
> +        std::cin >> data[i];
Обновил: https://contest.yandex.ru/contest/14768/run-report/23844310/

2019-11-12 07:06 UTC, ylyubimov approved these changes
Да, в целом Ок

2019-11-17 20:36 UTC, merged